spring.application.name=springbootwebtutorial
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:C:/Users/deepa/Documents/springbootwebtutorial
spring.datasource.username=deepakDB
spring.datasource.password=deepakj123
spring.jpa.hibernate.ddl-auto=update